spring.application.name=poc-sobrevidas
spring.datasource.url=jdbc:postgresql://localhost:5432/sobrevidas_db
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true